import React,{useState, useEffect} from 'react'

import { Loader, FormField, Card } from '../components'

const RenderCards= ({data,title})=>{
    if(data?.length >0){
        return data.map((post)=> <Card key= {post_id} {...post}/>)
    }

    return(<h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>{title}</h2>)
}

const Home = () => {
  const [loding, setLoding] = useState(false)
  const [allPosts, setAllPosts] = useState(null)
  const [searchText, setSearchText] = useState('')

  return (
    <section className='max-w-7xl mx-auto'>
        <div>
            <h1 className='font-extrabold text-[#222328] text-[32px]'>The Community Showcase</h1>
            <p className='mt-2 text-[#666e75] text-[14px] max-w-[500px]'>Browse through a collection of imaginate and visually stunning images generated by DALL-E AI</p>
        </div>
        <div className='mt-16'>
            <FormField/>
        </div>
        <div>
            {loding ? 
                (<div className='flex justify-center items-center'>
                    <Loader/>
                </div>):(
                    <>
                        {searchText && (<h2 className='font-medium text-[#666e75] text-xl mb-3'>Showing Results for <span className='text-[#222328]'/>{searchText}</h2>)}
                        <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
                            {searchText ? (
                                <RenderCards
                                    data={[]}
                                    title="No search result found"
                                />
                            ):(<RenderCards
                                data={[]}
                                title="No post found"
                            />)}
                        </div>
                    </>
                )
            }
        </div>
    </section>
  )
}

export default Home